#
# author: dts
# github: @conchoecia
# repository: @conchoecia/odp
#   date: 2022
#
# This is the example config file for odp_nway_rbh
#  - it is basically the sample config file as for odp
#
# For each run you can only pick n-way comparisons.
# In this example file, we can only specify 3-species
#  comparisons because we specified the option nways: 3
# You can pick as many species as you want as long as n >= 2
#
# The field num_permutations is the number of times the genomes
#  are shuffled to calculate the false discovery rate. Keep it to at least
#  1000000 permutations, but it is likely that doing many more than that
#  isn't useful.
#

nways: 3                 # This number should be the number of species that will be in each combination. Should match the number in analyses below.
search_method: "diamond" # this must be diamond or blastp
duplicate_proteins: "pass"    # currently only "fail" or "pass". Fail doesn't allow duplicate names or seqs
# These are all of the analyses that you would like to perform.
#  The things in quotes here are the 4-way comparisons that you would like to perform
#  We require these to be explicitely specified in this program because of the higher compute
#   time of each analysis. 
analyses:
  - ["CELE", "OTIP", "PEXS"]
  - ["CELE", "OTIP", "SRAT"]
  - ["CELE", "PEXS", "SRAT"]
  
num_permutations: 1000000

species:
  CELE:
    proteins: Nematoda/odp/CELE.faa
    chrom: Nematoda/odp/CELE.chrom
    genome: Nematoda/odp/CELE.fna
    minscafsize: 4500000
  OTIP:
    proteins: Nematoda/odp/OTIP.faa
    chrom: Nematoda/odp/OTIP.chrom
    genome: Nematoda/odp/OTIP.fna
    minscafsize: 4500000
  PEXS:
    proteins: Nematoda/odp/PEXS.faa
    chrom: Nematoda/odp/PEXS.chrom
    genome: Nematoda/odp/PEXS.fna
    minscafsize: 4500000
  SRAT:
    proteins: Nematoda/odp/SRAT.faa
    chrom: Nematoda/odp/SRAT.chrom
    genome: Nematoda/odp/SRAT.fna
    minscafsize: 4500000
