#' @title Extract Syntenic Architecture
#'
#' @description Consolidates Viterbi-inferred HMM classifications into contiguous
#' syntenic blocks and broad linkage groups, mapping algorithmic states back to physical coordinates.
#'
#' @param ref_species Character. Reference lineage identifier.
#' @param comp_species Character. Comparison lineage identifier.
#' @param comparison_type Character. Architecture of the comparison ("tip_vs_tip", "tip_vs_node").
#' @param hmm_class_path Character. Path to the HMM classification RDS generated by run_synteny_hmm.
#' @param config A `linguine_config` object containing spatial thresholds.
#'
#' @return A list containing paths to the strict blocks, broad regions, and classified genes RDS files.
#' @export
extract_synteny_architecture <- function(ref_species, comp_species, comparison_type, hmm_class_path, config) {

  if (comparison_type == "INode_vs_INode" || is.null(hmm_class_path)) {
    message("Bypassing architectural extraction for strictly structural Node-vs-Node analysis.")
    return(NULL)
  }

  broad_regions_path <- file.path(config$paths$results, paste0("broad_syntenic_regions_", ref_species, "_ref_", comp_species, "_comp.rds"))
  strict_blocks_path <- file.path(config$paths$results, paste0("strict_syntenic_blocks_", ref_species, "_ref_", comp_species, "_comp.rds"))
  classified_path <- file.path(config$paths$results, paste0("gene_observations_detailed_classified_", ref_species, "_vs_", comp_species, ".rds"))

  if (file.exists(broad_regions_path)) {
    message("Info: Scaffolding structures already extracted. Skipping.")
    return(list(strict_blocks = strict_blocks_path, broad_regions = broad_regions_path, classified_genes = classified_path))
  }

  message(sprintf("\n--- Extracting Contiguous Linkage Group Architecture (%s vs %s) ---", ref_species, comp_species))

  # ----------------------------------------------------------------------------
  # 1. Block Consolidation & Final Consensus
  # ----------------------------------------------------------------------------
  gene_obs <- readRDS(hmm_class_path)

  clean_data <- gene_obs |>
    dplyr::filter(!is.na(chromosome) & chromosome != "") |>
    dplyr::select(gene_id, chromosome, start, end, inferred_state_hmm1) |>
    dplyr::arrange(chromosome, start)

  final_synteny_report <- split(clean_data, clean_data$chromosome) |>
    purrr::map_dfr(~classify_chromosome_blocks(.x, config))

  block_data_for_join <- final_synteny_report |>
    dplyr::select(chromosome, block_start_pos = start_pos, block_end_pos = end_pos, inferred_state_blocks = inferred_state_final)

  gene_obs <- purrr::map2_dfr(
    split(gene_obs, gene_obs$chromosome),
    split(block_data_for_join, block_data_for_join$chromosome)[unique(gene_obs$chromosome)],
    map_blocks_to_genes
  )

  gene_obs <- gene_obs |>
    dplyr::mutate(
      final_synteny_classification = dplyr::case_when(
        stringr::str_detect(inferred_state_blocks, "SYN_TO") ~ dplyr::case_when(
          stringr::str_detect(reassigned_temp_observation, "^ON_") & !reassigned_temp_observation %in% c("ON_MULTIPLE_B_CHRS", "ON_NO_ORTHOLOG") ~ paste0("SYNTENIC_MATCH_", sub("^ON_", "", reassigned_temp_observation)),
          reassigned_temp_observation == "MULTIPLE_B_CHRS" ~ "SYNTENIC_MATCH_MULTIPLE_B_CHRS",
          reassigned_temp_observation == "NON_SYN_OBS" ~ "SYNTENIC_MATCH_NON_SYN_OBS",
          reassigned_temp_observation == "NO_ORTHOLOG" ~ "SYNTENIC_MATCH_NO_ORTHOLOG",
          TRUE ~ "SYNTENIC_MATCH_UNEXPECTED_OBSERVATION"
        ),
        stringr::str_detect(inferred_state_blocks, "TWO_CHR_MIX") | inferred_state_blocks %in% c("COMPLEX_REARRANGED", "UNCLEAR_NOISE") ~ inferred_state_blocks,
        TRUE ~ "UNEXPECTED_STATE"
      )
    )

  saveRDS(gene_obs, classified_path)

  # ----------------------------------------------------------------------------
  # 2. Extract Syntenic Blocks
  # ----------------------------------------------------------------------------
  original_ortholog_data <- readRDS(file.path(config$paths$processed_data, paste0(ref_species, "_vs_", comp_species, "_ortholog_data_filtered.rds")))

  syntenic_genes_df <- gene_obs |>
    dplyr::filter(stringr::str_detect(final_synteny_classification, "^SYNTENIC_MATCH_")) |>
    dplyr::mutate(target_comp_chromosome = stringr::str_replace(final_synteny_classification, "^SYNTENIC_MATCH_", "")) |>
    dplyr::arrange(chromosome, start)

  if (comparison_type != "tip_vs_tip") {
    syntenic_genes_df <- syntenic_genes_df |> dplyr::filter(stringr::str_detect(target_comp_chromosome, "^LG_"))
  }

  if (nrow(syntenic_genes_df) == 0) stop("Error: Zero 'SYNTENIC_MATCH' validations identified.")

  syntenic_blocks_prelim <- syntenic_genes_df |>
    dplyr::group_by(chromosome) |>
    dplyr::mutate(block_group_key = data.table::rleid(target_comp_chromosome)) |>
    dplyr::ungroup() |>
    dplyr::group_by(chromosome, target_comp_chromosome, block_group_key) |>
    dplyr::summarise(
      ref_block_start = min(start, na.rm = TRUE),
      ref_block_end = max(end, na.rm = TRUE),
      num_ref_genes_in_block = dplyr::n(),
      num_ref_OGs_in_block = length(unique(Orthogroup)),
      ref_gene_ids_in_block = list(gene_id),
      .groups = 'drop'
    ) |>
    dplyr::filter(num_ref_OGs_in_block >= config$thresholds$min_ogs_by_block) |>
    dplyr::arrange(chromosome, ref_block_start)

  # Coordinate Projections
  if (comparison_type == "tip_vs_tip") {
    ortho_unnested_strict <- syntenic_blocks_prelim |>
      dplyr::select(block_group_key, target_comp_chromosome, ref_gene_ids_in_block) |>
      tidyr::unnest(ref_gene_ids_in_block) |>
      dplyr::inner_join(original_ortholog_data, by = c("ref_gene_ids_in_block" = "ref_gene_id", "target_comp_chromosome" = "comp_chromosome"))
      
    ortho_agg_strict <- ortho_unnested_strict |>
      dplyr::group_by(block_group_key) |>
      dplyr::summarise(
        comp_block_start = min(comp_start, na.rm = TRUE),
        comp_block_end = max(comp_end, na.rm = TRUE),
        comp_gene_ids_in_block = list(unique(comp_gene_id)),
        .groups = "drop"
      )
      
    final_syntenic_blocks <- syntenic_blocks_prelim |>
      dplyr::left_join(ortho_agg_strict, by = "block_group_key") |>
      dplyr::filter(!is.na(comp_block_start) & !is.na(comp_block_end)) |>
      dplyr::mutate(
        comp_gene_ids_in_block = lapply(comp_gene_ids_in_block, function(x) if(is.null(x)) character(0) else x)
      ) |>
      dplyr::select(-block_group_key)
  } else {
    ortho_unnested_node <- syntenic_blocks_prelim |>
      dplyr::select(block_group_key, ref_gene_ids_in_block) |>
      tidyr::unnest(ref_gene_ids_in_block) |>
      dplyr::inner_join(original_ortholog_data, by = c("ref_gene_ids_in_block" = "ref_gene_id"))
      
    ortho_agg_node <- ortho_unnested_node |>
      dplyr::group_by(block_group_key) |>
      dplyr::summarise(
        comp_block_start = min(ref_start, na.rm = TRUE),
        comp_block_end = max(ref_end, na.rm = TRUE),
        .groups = "drop"
      )
      
    final_syntenic_blocks <- syntenic_blocks_prelim |>
      dplyr::left_join(ortho_agg_node, by = "block_group_key") |>
      dplyr::filter(!is.na(comp_block_start) & !is.na(comp_block_end)) |>
      dplyr::mutate(
        comp_gene_ids_in_block = list(character(0))
      ) |>
      dplyr::select(-block_group_key)
  }

  saveRDS(final_syntenic_blocks, strict_blocks_path)

  # ----------------------------------------------------------------------------
  # 3. Scaffold Broad Linkage Regions
  # ----------------------------------------------------------------------------
  broad_syntenic_regions_coords <- final_syntenic_blocks |>
    dplyr::arrange(chromosome, ref_block_start) |>
    dplyr::group_by(chromosome) |>
    dplyr::mutate(broad_block_key = data.table::rleid(target_comp_chromosome)) |>
    dplyr::ungroup() |>
    dplyr::group_by(chromosome, target_comp_chromosome, broad_block_key) |>
    dplyr::summarise(
      broad_ref_start = min(ref_block_start, na.rm = TRUE),
      broad_ref_end = max(ref_block_end, na.rm = TRUE),
      num_strict_blocks_merged = dplyr::n(),
      broad_comp_start_initial = min(comp_block_start, na.rm = TRUE),
      broad_comp_end_initial = max(comp_block_end, na.rm = TRUE),
      ref_gene_ids_in_strict_blocks = list(unique(unlist(ref_gene_ids_in_block))),
      .groups = 'drop'
    ) |>
    dplyr::arrange(chromosome, broad_ref_start)

  if (comparison_type == "tip_vs_tip") {
    # Fast spatial overlap using foverlaps wrapper
    broad_coords_for_join <- broad_syntenic_regions_coords |>
      dplyr::mutate(block_id = as.character(broad_block_key)) |>
      dplyr::select(block_id, chromosome, block_start_pos = broad_ref_start, block_end_pos = broad_ref_end, inferred_state_blocks = target_comp_chromosome)
    
    mapped_genes <- map_blocks_to_genes(gene_obs, broad_coords_for_join)
    
    # Aggregate reference genes
    ref_genes_agg <- mapped_genes |>
      dplyr::filter(!is.na(block_id)) |>
      dplyr::group_by(block_id, chromosome) |>
      dplyr::summarise(broad_ref_gene_ids = list(unique(gene_id)), .groups = "drop")
      
    broad_syntenic_regions <- broad_syntenic_regions_coords |>
      dplyr::mutate(block_id = as.character(broad_block_key)) |>
      dplyr::left_join(ref_genes_agg, by = c("block_id", "chromosome")) |>
      dplyr::mutate(broad_ref_gene_ids = lapply(broad_ref_gene_ids, function(x) if(is.null(x)) character(0) else x))
      
    # Optimize ortholog mapping using unnest and join
    ortho_unnested <- broad_syntenic_regions |>
      dplyr::select(block_id, target_comp_chromosome, broad_ref_gene_ids) |>
      tidyr::unnest(broad_ref_gene_ids) |>
      dplyr::inner_join(original_ortholog_data, by = c("broad_ref_gene_ids" = "ref_gene_id", "target_comp_chromosome" = "comp_chromosome"))
      
    ortho_agg <- ortho_unnested |>
      dplyr::group_by(block_id) |>
      dplyr::summarise(
        broad_comp_gene_ids = list(unique(comp_gene_id)),
        broad_comp_start = min(comp_start, na.rm = TRUE),
        broad_comp_end = max(comp_end, na.rm = TRUE),
        .groups = "drop"
      )
      
    broad_syntenic_regions <- broad_syntenic_regions |>
      dplyr::left_join(ortho_agg, by = "block_id") |>
      dplyr::mutate(
        broad_comp_gene_ids = lapply(broad_comp_gene_ids, function(x) if(is.null(x)) character(0) else x),
        broad_comp_start = ifelse(is.na(broad_comp_start), NA_real_, broad_comp_start),
        broad_comp_end = ifelse(is.na(broad_comp_end), NA_real_, broad_comp_end)
      ) |>
      dplyr::select(-block_id)
  } else {
    broad_syntenic_regions <- broad_syntenic_regions_coords |>
      dplyr::mutate(
        broad_ref_gene_ids = ref_gene_ids_in_strict_blocks,
        broad_comp_gene_ids = list(character(0)),
        broad_comp_start = broad_comp_start_initial,
        broad_comp_end = broad_comp_end_initial
      )
  }

  broad_syntenic_regions <- broad_syntenic_regions |>
    dplyr::select(chromosome, broad_ref_start, broad_ref_end, target_comp_chromosome, broad_comp_start, broad_comp_end, num_strict_blocks_merged, broad_ref_gene_ids, broad_comp_gene_ids)

  # Nomenclature Mapping
  linkage_group_definitions <- broad_syntenic_regions |>
    dplyr::rowwise() |>
    dplyr::mutate(n_genes = length(broad_ref_gene_ids)) |>
    dplyr::ungroup() |>
    dplyr::group_by(chromosome, target_comp_chromosome) |>
    dplyr::summarise(total_genes = sum(n_genes), .groups = 'drop') |>
    dplyr::filter(total_genes >= config$thresholds$min_final_block_size) |>
    dplyr::arrange(dplyr::desc(total_genes)) |>
    dplyr::mutate(linkage_group_name = sprintf("LG_%03d", dplyr::row_number())) |>
    dplyr::select(chromosome, target_comp_chromosome, linkage_group_name)

  broad_syntenic_regions_final <- broad_syntenic_regions |>
    dplyr::left_join(linkage_group_definitions, by = c("chromosome", "target_comp_chromosome")) |>
    dplyr::select(linkage_group_name, dplyr::everything())

  saveRDS(broad_syntenic_regions_final, broad_regions_path)
  message("Structural architectural blocks successfully cached.")

  return(list(strict_blocks = strict_blocks_path, broad_regions = broad_regions_path, classified_genes = classified_path))
}


#' @title Plot Syntenic Summary Statistics
#'
#' @description Generates visual distributions and karyoplots to map algorithmic
#' blocks back to physical scaffolds.
#'
#' @param ref_species Character. Reference lineage.
#' @param comp_species Character. Comparison lineage.
#' @param comparison_type Character. Architecture of the comparison.
#' @param config A `linguine_config` object.
#'
#' @return Invisible NULL. Saves plots to the configured plots directory.
#' @export
plot_synteny_summary <- function(ref_species, comp_species, comparison_type, config) {

  if (comparison_type == "INode_vs_INode") {
    message("Bypassing intermediate visualization for structural Node-vs-Node analysis.")
    return(invisible(NULL))
  }

  linkage_groups_plot_path <- file.path(config$paths$plots, paste0("linear_chromosome_linkage_groups_", ref_species, "_vs_", comp_species, ".png"))
  if (file.exists(linkage_groups_plot_path)) {
    message("Info: Graphical summaries already generated. Skipping.")
    return(invisible(NULL))
  }

  message("--- Generating Pairwise Syntenic Analytics ---")

  classified_synteny_df <- readRDS(file.path(config$paths$results, paste0("gene_observations_detailed_classified_", ref_species, "_vs_", comp_species, ".rds")))
  broad_syntenic_regions_df <- readRDS(file.path(config$paths$results, paste0("broad_syntenic_regions_", ref_species, "_ref_", comp_species, "_comp.rds")))
  ref_chromosome_sizes_df <- readRDS(file.path(config$paths$processed_data, paste0(ref_species, "_chromosome_sizes.rds")))

  chr_order_by_size <- ref_chromosome_sizes_df |> dplyr::arrange(dplyr::desc(chromosome_length_bp)) |> dplyr::pull(ref_chromosome)

  # Base colors mapping
  all_final_classifications <- unique(classified_synteny_df$final_synteny_classification)
  base_colors_map <- c(
    "COMPLEX_REARRANGED" = "#C42C1E", "TWO_CHR_MIX" = "#996633", "SYNTENIC_MATCH_NON_SYN_OBS" = "#4991A5",
    "SYNTENIC_MATCH_MULTIPLE_B_CHRS" = "#74A9CF", "SYNTENIC_MATCH_NO_ORTHOLOG" = "#A6BDDB",
    "UNCLEAR_NOISE" = "#D9D9D9", "UNEXPECTED_STATE" = "black"
  )

  unique_chr_ids <- classified_synteny_df |>
    dplyr::pull(final_synteny_classification) |>
    stringr::str_match(paste0("SYNTENIC_MATCH_", "(.*)")) |>
    _[, 2] |> na.omit() |> unique() |> sort()

  unique_chr_ids <- setdiff(unique_chr_ids, c("NON_SYN_OBS", "MULTIPLE_B_CHRS", "NO_ORTHOLOG"))

  generated_colors <- character(0)
  if (length(unique_chr_ids) > 0) {
    generated_colors <- scales::hue_pal(l = 60, c = 100)(length(unique_chr_ids))
    names(generated_colors) <- paste0("SYNTENIC_MATCH_", unique_chr_ids)
  }
  color_palette_final <- c(generated_colors, base_colors_map)

  # Stacked Distribution Plot
  chromosome_final_summary <- classified_synteny_df |>
    dplyr::group_by(chromosome, final_synteny_classification) |> dplyr::count() |>
    dplyr::ungroup() |> dplyr::group_by(chromosome) |> dplyr::mutate(percentage = n / sum(n) * 100)

  plot_chr_dist <- ggplot2::ggplot(chromosome_final_summary, ggplot2::aes(x = chromosome, y = percentage, fill = final_synteny_classification)) +
    ggplot2::geom_bar(stat = "identity") +
    ggplot2::labs(title = paste0("Syntenic State Distribution (", ref_species, " vs ", comp_species, ")"), x = "Ref Chromosome", y = "% Genes") +
    ggplot2::theme_minimal() + ggplot2::theme(axis.text.x = ggplot2::element_text(angle = 45, hjust = 1)) +
    ggplot2::scale_fill_manual(values = color_palette_final)

  ggplot2::ggsave(file.path(config$paths$plots, paste0("chromosome_final_state_distribution_", ref_species, "_vs_", comp_species, ".png")), plot_chr_dist, width = 12, height = 7, dpi = 300, bg = "white")

  # Karyoplot: Strict Delineations
  inferred_blocks_df <- classified_synteny_df |>
    dplyr::arrange(chromosome, start) |> dplyr::group_by(chromosome) |>
    dplyr::mutate(block_id = data.table::rleid(final_synteny_classification)) |> dplyr::ungroup() |>
    dplyr::group_by(chromosome, block_id, final_synteny_classification) |>
    dplyr::summarise(block_start = min(start), block_end = max(end), .groups = 'drop') |>
    dplyr::left_join(ref_chromosome_sizes_df, by = c("chromosome" = "ref_chromosome")) |>
    dplyr::mutate(chromosome = factor(chromosome, levels = chr_order_by_size))

  plot_linear_blocks <- ggplot2::ggplot(inferred_blocks_df, ggplot2::aes(y = chromosome)) +
    ggplot2::geom_rect(ggplot2::aes(xmin = 1, xmax = chromosome_length_bp, ymin = as.numeric(chromosome) - 0.45, ymax = as.numeric(chromosome) + 0.45), fill = "lightgray", color = "grey50", linewidth = 0.2) +
    ggplot2::geom_rect(ggplot2::aes(xmin = block_start, xmax = block_end, fill = final_synteny_classification, ymin = as.numeric(chromosome) - 0.4, ymax = as.numeric(chromosome) + 0.4)) +
    ggplot2::scale_fill_manual(values = color_palette_final) +
    ggplot2::labs(title = paste0("Syntenic Blocks (Detailed) - ", ref_species, " vs ", comp_species), x = "Position (bp)", y = "Ref Chromosome") +
    ggplot2::theme_minimal() + ggplot2::theme(legend.position = "bottom")

  ggplot2::ggsave(file.path(config$paths$plots, paste0("linear_chromosome_final_blocks_", ref_species, "_vs_", comp_species, ".png")), plot_linear_blocks, width = 14, height = 9, dpi = 300, bg = "white")

  # Karyoplot: Broad Scaffolding
  broad_regions_plot <- broad_syntenic_regions_df |>
    dplyr::left_join(ref_chromosome_sizes_df, by = c("chromosome" = "ref_chromosome")) |>
    dplyr::mutate(chromosome = factor(chromosome, levels = chr_order_by_size))

  unique_lgs <- sort(unique(broad_regions_plot$linkage_group_name))
  lg_colors <- scales::hue_pal()(length(unique_lgs))
  names(lg_colors) <- unique_lgs

  plot_linear_lgs <- ggplot2::ggplot(broad_regions_plot, ggplot2::aes(y = chromosome)) +
    ggplot2::geom_rect(ggplot2::aes(xmin = 1, xmax = chromosome_length_bp, ymin = as.numeric(chromosome) - 0.45, ymax = as.numeric(chromosome) + 0.45), fill = "lightgray", color = "grey50", linewidth = 0.2) +
    ggplot2::geom_rect(ggplot2::aes(xmin = broad_ref_start, xmax = broad_ref_end, fill = linkage_group_name, ymin = as.numeric(chromosome) - 0.4, ymax = as.numeric(chromosome) + 0.4)) +
    ggplot2::scale_fill_manual(values = lg_colors) +
    ggplot2::labs(title = paste0("Broad Linkage Groups - ", ref_species, " vs ", comp_species), x = "Position (bp)", y = "Ref Chromosome") +
    ggplot2::theme_minimal() + ggplot2::theme(legend.position = "bottom")

  ggplot2::ggsave(linkage_groups_plot_path, plot_linear_lgs, width = 14, height = 9, dpi = 300, bg = "white")

  message("Graphical summaries complete.")
}
